apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: gcr.io/gke-lab-go/transaction-postgres-db:v2
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "pass"
        - name: POSTGRES_DB
          value: "postgres_db"
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-api-server
  template:
    metadata:
      labels:
        app: transaction-api-server
    spec:
      containers:
      - name: transaction-api-server
        image: gcr.io/gke-lab-go/transaction-api-server:v2
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-api-server-service
spec:
  selector:
    app: transaction-api-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer
