// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEmpty) Reset() {
	*x = TransactionEmpty{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEmpty) ProtoMessage() {}

func (x *TransactionEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEmpty.ProtoReflect.Descriptor instead.
func (*TransactionEmpty) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      string                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

type TransactionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TransactionTypeId int32                  `protobuf:"varint,2,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount            float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TransactionRequest) GetTransactionTypeId() int32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *TransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransactionIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionIdResponse) Reset() {
	*x = TransactionIdResponse{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionIdResponse) ProtoMessage() {}

func (x *TransactionIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionIdResponse.ProtoReflect.Descriptor instead.
func (*TransactionIdResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionIdResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type TransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId         int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TransactionTypeId int32                  `protobuf:"varint,3,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount            float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionDate   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *TransactionResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TransactionResponse) GetTransactionTypeId() int32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *TransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetTransactionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

type TransactionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionListResponse) Reset() {
	*x = TransactionListResponse{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionListResponse) ProtoMessage() {}

func (x *TransactionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionListResponse.ProtoReflect.Descriptor instead.
func (*TransactionListResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionListResponse) GetTransactions() []*TransactionResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TransactionJoinAccountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Document        string                 `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount          float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionJoinAccountResponse) Reset() {
	*x = TransactionJoinAccountResponse{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionJoinAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionJoinAccountResponse) ProtoMessage() {}

func (x *TransactionJoinAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionJoinAccountResponse.ProtoReflect.Descriptor instead.
func (*TransactionJoinAccountResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionJoinAccountResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *TransactionJoinAccountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransactionJoinAccountResponse) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *TransactionJoinAccountResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionJoinAccountResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionJoinAccountResponse) GetTransactionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

type TransactionAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Document      string                 `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionAmountResponse) Reset() {
	*x = TransactionAmountResponse{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAmountResponse) ProtoMessage() {}

func (x *TransactionAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAmountResponse.ProtoReflect.Descriptor instead.
func (*TransactionAmountResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionAmountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransactionAmountResponse) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *TransactionAmountResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransactionAmountListResponse struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	TransactionsAmount []*TransactionAmountResponse `protobuf:"bytes,1,rep,name=transactionsAmount,proto3" json:"transactionsAmount,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionAmountListResponse) Reset() {
	*x = TransactionAmountListResponse{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAmountListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAmountListResponse) ProtoMessage() {}

func (x *TransactionAmountListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAmountListResponse.ProtoReflect.Descriptor instead.
func (*TransactionAmountListResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionAmountListResponse) GetTransactionsAmount() []*TransactionAmountResponse {
	if x != nil {
		return x.TransactionsAmount
	}
	return nil
}

type TransactionJoinAccountListResponse struct {
	state                 protoimpl.MessageState            `protogen:"open.v1"`
	TransactionsByAccount []*TransactionJoinAccountResponse `protobuf:"bytes,1,rep,name=transactionsByAccount,proto3" json:"transactionsByAccount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransactionJoinAccountListResponse) Reset() {
	*x = TransactionJoinAccountListResponse{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionJoinAccountListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionJoinAccountListResponse) ProtoMessage() {}

func (x *TransactionJoinAccountListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionJoinAccountListResponse.ProtoReflect.Descriptor instead.
func (*TransactionJoinAccountListResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionJoinAccountListResponse) GetTransactionsByAccount() []*TransactionJoinAccountResponse {
	if x != nil {
		return x.TransactionsByAccount
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vtransaction\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\x12\n" +
	"\x10TransactionEmpty\"&\n" +
	"\bDocument\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\"{\n" +
	"\x12TransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12.\n" +
	"\x13transaction_type_id\x18\x02 \x01(\x05R\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\">\n" +
	"\x15TransactionIdResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"\xea\x01\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12.\n" +
	"\x13transaction_type_id\x18\x03 \x01(\x05R\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12E\n" +
	"\x10transaction_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionDate\"_\n" +
	"\x17TransactionListResponse\x12D\n" +
	"\ftransactions\x18\x01 \x03(\v2 .transaction.TransactionResponseR\ftransactions\"\xf8\x01\n" +
	"\x1eTransactionJoinAccountResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdocument\x18\x03 \x01(\tR\bdocument\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12E\n" +
	"\x10transaction_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionDate\"c\n" +
	"\x19TransactionAmountResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"w\n" +
	"\x1dTransactionAmountListResponse\x12V\n" +
	"\x12transactionsAmount\x18\x01 \x03(\v2&.transaction.TransactionAmountResponseR\x12transactionsAmount\"\x87\x01\n" +
	"\"TransactionJoinAccountListResponse\x12a\n" +
	"\x15transactionsByAccount\x18\x01 \x03(\v2+.transaction.TransactionJoinAccountResponseR\x15transactionsByAccount2\xed\x03\n" +
	"\x12TransactionService\x12W\n" +
	"\x10listTransactions\x12\x1d.transaction.TransactionEmpty\x1a$.transaction.TransactionListResponse\x12X\n" +
	"\x11CreateTransaction\x12\x1f.transaction.TransactionRequest\x1a\".transaction.TransactionIdResponse\x12[\n" +
	"\x16ListTransactionsAmount\x12\x15.transaction.Document\x1a*.transaction.TransactionAmountListResponse\x12a\n" +
	"\x1bListTransactionsByAccountId\x12\x11.common.AccountId\x1a/.transaction.TransactionJoinAccountListResponse\x12d\n" +
	"\x1aListTransactionsByDocument\x12\x15.transaction.Document\x1a/.transaction.TransactionJoinAccountListResponseB\vZ\t/pb;protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_transaction_proto_goTypes = []any{
	(*TransactionEmpty)(nil),                   // 0: transaction.TransactionEmpty
	(*Document)(nil),                           // 1: transaction.Document
	(*TransactionRequest)(nil),                 // 2: transaction.TransactionRequest
	(*TransactionIdResponse)(nil),              // 3: transaction.TransactionIdResponse
	(*TransactionResponse)(nil),                // 4: transaction.TransactionResponse
	(*TransactionListResponse)(nil),            // 5: transaction.TransactionListResponse
	(*TransactionJoinAccountResponse)(nil),     // 6: transaction.TransactionJoinAccountResponse
	(*TransactionAmountResponse)(nil),          // 7: transaction.TransactionAmountResponse
	(*TransactionAmountListResponse)(nil),      // 8: transaction.TransactionAmountListResponse
	(*TransactionJoinAccountListResponse)(nil), // 9: transaction.TransactionJoinAccountListResponse
	(*timestamppb.Timestamp)(nil),              // 10: google.protobuf.Timestamp
	(*AccountId)(nil),                          // 11: common.AccountId
}
var file_transaction_proto_depIdxs = []int32{
	10, // 0: transaction.TransactionResponse.transaction_date:type_name -> google.protobuf.Timestamp
	4,  // 1: transaction.TransactionListResponse.transactions:type_name -> transaction.TransactionResponse
	10, // 2: transaction.TransactionJoinAccountResponse.transaction_date:type_name -> google.protobuf.Timestamp
	7,  // 3: transaction.TransactionAmountListResponse.transactionsAmount:type_name -> transaction.TransactionAmountResponse
	6,  // 4: transaction.TransactionJoinAccountListResponse.transactionsByAccount:type_name -> transaction.TransactionJoinAccountResponse
	0,  // 5: transaction.TransactionService.listTransactions:input_type -> transaction.TransactionEmpty
	2,  // 6: transaction.TransactionService.CreateTransaction:input_type -> transaction.TransactionRequest
	1,  // 7: transaction.TransactionService.ListTransactionsAmount:input_type -> transaction.Document
	11, // 8: transaction.TransactionService.ListTransactionsByAccountId:input_type -> common.AccountId
	1,  // 9: transaction.TransactionService.ListTransactionsByDocument:input_type -> transaction.Document
	5,  // 10: transaction.TransactionService.listTransactions:output_type -> transaction.TransactionListResponse
	3,  // 11: transaction.TransactionService.CreateTransaction:output_type -> transaction.TransactionIdResponse
	8,  // 12: transaction.TransactionService.ListTransactionsAmount:output_type -> transaction.TransactionAmountListResponse
	9,  // 13: transaction.TransactionService.ListTransactionsByAccountId:output_type -> transaction.TransactionJoinAccountListResponse
	9,  // 14: transaction.TransactionService.ListTransactionsByDocument:output_type -> transaction.TransactionJoinAccountListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
